---
theme                   : jekyll-agency

url                     : https://rieselbar.de
baseurl                 : '' # the subpath of your site, e.g. /blog

title                   : Unverpackt München Nord - die Rieselbar
email                   : info@rieselbar.de
description             : Unverpackt einkaufen in München Nord
image                   :
  path: assets/img/logo/gefaesse_noBackground.png
  width: 100
  height: 100
author                  : Benedikt Häuser
logo                    : ../../assets/img/logo/gefaesse_noBackground.png
logo-height             : 80 #height in px, defaults to 52px
google_site_verification: i7xJzIzAxyRZpOsJseu9IpQMOIfIaxJU9DLb4aO03pI
locale                  : de

collections             :
  portfolio:
  organisation_de:
  organisation_en:

plugins                 :
  - jekyll-seo-tag

markdown                : kramdown
