name: Build and deploy Jekyll site to Azure Blob static page

on:
  push:
    branches:
      - '**'

permissions:
      id-token: write
      contents: read

jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: lemonarc/jekyll-action@1.0.0
    # - uses: haya14busa/action-cond@v1
    #   id: targetFolder
    #   with:
    #     cond: ${{ github.ref_name ==  'main' }}
    #     if_true: '$web'
    #     if_false: '$web/${{ github.ref_name }}'

    - name: Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.SUBSCRIPTION_ID}}

    - name: storage upload
      run: |
        az storage blob upload-batch --destination "$web" --source "_site" --account-name  ${{ secrets.STORAGE_ACCOUNT_NAME }} --overwrite true --auth-mode login

    # - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
    #   with:
    #     source_dir: '_site'
    #     container_name: ${{ steps.targetFolder.outputs.value }}
    #     sas_token: ${{ secrets.sas_token }}
    #     account_name: ${{ secrets.storage_account_name }} 
    #     extra_args: --overwrite True
    #     sync: true

    - name: cdn endpoint purge
      run: |
        az cdn endpoint purge -g domain_unverpacktladen -n cdnEndpointUnverpacktWebsite --profile-name cdnProfileUnverpacktWebsite --content-paths '/*'
