---
name       : deployment

on         :
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs       :
  jekyll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: preparations
        shell: bash
        run: |
          git config --global --add safe.directory /github/workspace

      # - uses: jdx/mise-action@v2
      #   with:
      #     cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID}}

      - name: storage upload
        run: |
          az storage blob upload-batch --destination \$web --source '_site' --account-name  ${{ secrets.STORAGE_ACCOUNT_NAME }} --overwrite true --auth-mode login

      - name: cdn endpoint purge
        run: |
          az cdn endpoint purge -g domain_unverpacktladen -n cdnEndpointUnverpacktWebsite --profile-name cdnProfileUnverpacktWebsite --content-paths '/*'
